<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form enctype="multipart/form-data" method="post" action="/file">
    <p>Загрузите ваши файлы на сервер</p>
    <p><input type="file" name="file" accept="text/xml">
        <input type="submit" value="Отправить"></p>
</form>

<div>
    <a href="/history">history</a>
    <a href="/securities">securities</a>
    <a href="/common/">common table</a>
</div>
</body>
</html>